# Makefile autogenerated by premake
# Don't edit this file! Instead edit `premake.lua` then rerun `make`
# Options:
#   CONFIG=[Debug|Release]

ifndef CONFIG
  CONFIG=Debug
endif

export CONFIG

.PHONY: all clean claro-base claro-graphics

all: claro-base claro-graphics

Makefile: premake.lua src/claro/base/premake.lua src/claro/graphics/premake.lua
	@echo ==== Regenerating Makefiles ====
	@premake --file $^ src/claro/base/premake.lua src/claro/graphics/premake.lua src/claro/base/premake.lua src/claro/graphics/premake.lua src/claro/base/premake.lua src/claro/graphics/premake.lua --target gnu --os macosx

claro-base:
	@echo ==== Building claro-base ====
	@$(MAKE) --no-print-directory -C src/claro/base

claro-graphics:
	@echo ==== Building claro-graphics ====
	@$(MAKE) --no-print-directory -C src/claro/graphics

clean:
	@$(MAKE) --no-print-directory -C src/claro/base clean
	@$(MAKE) --no-print-directory -C src/claro/graphics clean
