# Makefile autogenerated by premake
# Don't edit this file! Instead edit `premake.lua` then rerun `make`
# Options:
#   CONFIG=[Debug|Release]

ifndef CONFIG
  CONFIG=Debug
endif

export CONFIG

.PHONY: all clean claro-base claro-graphics claro-graphics-widgets claro-graphics-platform

all: claro-base claro-graphics claro-graphics-widgets claro-graphics-platform

Makefile: premake.lua src/claro/base/premake.lua src/claro/graphics/premake.lua src/claro/graphics/widgets/premake.lua src/claro/graphics/platform/premake.lua
	@echo ==== Regenerating Makefiles ====
	@premake --file $^ --target gnu --os linux

claro-base:
	@echo ==== Building claro-base ====
	@$(MAKE) --no-print-directory -C src/claro/base

claro-graphics: claro-base claro-graphics-widgets claro-graphics-platform
	@echo ==== Building claro-graphics ====
	@$(MAKE) --no-print-directory -C src/claro/graphics

claro-graphics-widgets:
	@echo ==== Building claro-graphics-widgets ====
	@$(MAKE) --no-print-directory -C src/claro/graphics/widgets

claro-graphics-platform:
	@echo ==== Building claro-graphics-platform ====
	@$(MAKE) --no-print-directory -C src/claro/graphics/platform

clean:
	@$(MAKE) --no-print-directory -C src/claro/base clean
	@$(MAKE) --no-print-directory -C src/claro/graphics clean
	@$(MAKE) --no-print-directory -C src/claro/graphics/widgets clean
	@$(MAKE) --no-print-directory -C src/claro/graphics/platform clean
